groups:
  - name: my-alerts
    interval: 15s
    rules:
      - alert: NodeDown
        expr: up{job="node"} == 0
        for: 2m
        labels:
          team: infra
          env: prod
        annotations:
          message: "instance {{.Labels.instance}} is currently down"

      - alert: DatabaseDown
        expr: up{job="db"} == 0
        for: 0m
        labels:
          team: database
          env: prod
        annotations:
          message: "{{.Labels.instance}} is currently down"

      - alert: DatabaseDown-dev
        expr: up{job="db2"} == 0
        for: 0m
        labels:
          team: database
          env: dev
        annotations:
          message: "instance {{.Labels.instance}} is currently down"